---
name: EventBonus
version: 0.1.0
main: lentou\EventBonus\Main
author: lentou
api: 4.0.0

permissions:
  lentou.eventbonus.command:
    default: op
    description: "the main command of eventbonus"
...
